version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.Production
    volumes:
      - ./:/go/src/app
    ports:
      - "3000:8080"
    entrypoint: ['/usr/local/bin/entrypoint.sh']
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7032:5432"
